services:
  - type: web
    name: pamsforce-admin
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://serverapp-a8wy.onrender.com/api
